### ISSUE TITLE
Crash on start: List index out of range

### ISSUE THREAD

**Issue by yeraydiazdiaz** [sublimelsp/LSP-elixir#18]
Hello, thanks for the work on LSP-elixir 🙏🏻 

I'm having trouble installing it, although it seems some of the functionality does work. Specifically, shortly after starting ST4 I get a dialog saying:

> Could not start elixir-ls
> list index out of range
> Server will be disabled for this window

When I open the console there's the following output:

```
Failed to register plugin ""
Traceback (most recent call last):
  File "/Users/yeray/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 602, in _register_plugin_impl
    if client_configs.add_external_config(name, settings, base_file, notify_listener):
  File "/Users/yeray/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/settings.py", line 37, in add_external_config
    config = ClientConfig.from_sublime_settings(name, s, file)
  File "/Users/yeray/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 566, in from_sublime_settings
    base = sublime.decode_value(sublime.load_resource(file))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 436, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages//.sublime-settings" not found

Unable to start elixir-ls
Traceback (most recent call last):
  File "/Users/yeray/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 332, in start_async
    transport = create_transport(transport_config, cwd, session)
  File "/Users/yeray/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 207, in create_transport
    process = start_subprocess()
  File "/Users/yeray/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 196, in start_subprocess
    return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
  File "/Users/yeray/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 277, in _start_subprocess
    cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1351, in _execute_child
IndexError: list index out of range
```

I tried digging a bit and get a root cause but I don't have a lot of experience with ST plugins and LSP. I'd be happy to have a look myself with some guidance though.

Thanks again.

*Update*: I forgot to include some details about my system:
- Mac OS X Catalina
- ST4 build 4099

**Comment by yeraydiazdiaz** [comment]
After reinstalling the packages the error is not happening anymore.
