### ISSUE TITLE
Error on hover

### ISSUE THREAD

**Issue by sardaukar** [sublimelsp/LSP-elixir#42]
I see this in the log panel when I hover over functions with no docs

```
:: [14:54:40.894] <-  lsp-elixir window/logMessage: {'message': 'Process #PID<0.1621.0> raised an exception\n** (FunctionClauseError) no function clause matching in String.split/3\n    (elixir 1.15.0) lib/string.ex:478: String.split(nil, "\\n\\n", [parts: 2])\n    (language_server 0.15.1) lib/language_server/providers/hover.ex:59: ElixirLS.LanguageServer.Providers.Hover.add_hexdocs_link/3\n    (language_server 0.15.1) lib/language_server/providers/hover.ex:54: ElixirLS.LanguageServer.Providers.Hover.contents/3\n    (language_server 0.15.1) lib/language_server/providers/hover.ex:32: ElixirLS.LanguageServer.Providers.Hover.hover/4\n    (language_server 0.15.1) lib/language_server/server.ex:834: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2', 'type': 1}
```

**Comment by rchl** [comment]
Feel free to report in https://github.com/elixir-lsp/elixir-ls/

**Comment by sardaukar** [comment]
Oh, sorry - thought this was the repo for it :pray:
